blog/urls.py
from django.urls import path
from . import views
from django.contrib.auth import login
from blog import views
from django.contrib.auth import views as auth_views
from django.conf.urls import url
from django.conf.urls import include

urlpatterns = [
    
    path('', views.loginview, name='loginview'),
    path('blog', views.blog, name='blog'),
    path('administrador', views.administradores, name='administrador'),
    path('ListaVendedores', views.ListaVendedores, name='ListaVendedores'),
    path('MantenedorOfertas', views.MantenedorOfertas, name='MantenedorOfertas'),
    path('MantenedorTienda', views.MantenedorTienda, name='MantenedorTienda'),
    path('MantenedorVendedor', views.MantenedorVendedor, name='MantenedorVendedor'),
    path('RegistrarVendedor', views.Registrar_Vendedor, name='RegistrarVendedor'),
    path('Login', views.login_user, name="login"),
    path('RegistrarTienda', views.registrarTienda, name='RegistrarTienda'),
    path('RegistrarOferta', views.registrarOferta, name='RegistrarOferta'),

    # Necesario para allauth
    path('blog/', include('allauth.urls')),
    url('blog', include('social_django.urls', namespace='social')),
   # (r'^blog/$', 'django.contrib.auth.views.login'),

]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blog.urls')),
    
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.dispatch import receiver
from allauth.account.signals import user_signed_up

class Post(models.Model):
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(
            default=timezone.now)
    published_date = models.DateTimeField(
            blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

@receiver(user_signed_up)
def create_user_profile(request, user, **kwargs):
    profile = Profile.objects.create(user=user)
    profile.save()

class Usuario(User):
    nombre = models.CharField(max_length=16)
    apellido = models.CharField(max_length=16)

    def __str__(self):
        return self.username


class Tienda(models.Model):
    nombret = models.CharField(max_length=50)
    direccion = models.CharField(max_length=50)
    ciudad = models.CharField(max_length=50)
    comuna = models.CharField(max_length=50)
    telefono = models.CharField(max_length=9)
    encargado = models.CharField(max_length=50)

    def __str__(self):
        return self.nombret

    class Meta:
        verbose_name="Tienda"
        verbose_name_plural="Tiendas"

class Producto(models.Model):
    idp = models.CharField(max_length=10)
    nombrep = models.CharField(max_length=50)
    descripcion = models.CharField(max_length=50)
    precio = models.CharField(max_length=50)
    tipo_producto = models.CharField(max_length=50)

    def __str__(self):
        return self.idp

    class Meta:
        verbose_name="Producto"
        verbose_name_plural="Productos"

class Vendedor(models.Model):
    nombreve = models.CharField(max_length=50)
    Tienda = models.ForeignKey(Tienda, on_delete=models.CASCADE)

    def __str__(self):
        return self.nombreve

    class Meta:
        verbose_name="Vendedor"
        verbose_name_plural="Vendedores"

class Venta(models.Model):
    idv = models.CharField(max_length=50)
    fecha = models.DateTimeField(blank=True, null=True)
    cantidad = models.CharField(max_length=10)
    sucursal = models.CharField(max_length=50)
    Vendedor = models.ForeignKey(Usuario, on_delete=models.CASCADE)

    def __str__(self):
        return self.idv

class Oferta(models.Model):
    ido = models.CharField(max_length=10)
    Producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    valor_oferta = models.CharField(max_length=4)
    descripcion = models.CharField(max_length=50)

    def __str__(self):
        return self.ido

blog/views.py
from django.http import *
from django.shortcuts import render, render_to_response
from django.views.decorators.csrf import csrf_protect
from django.template import RequestContext
from .models import *
from django.utils import timezone
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.hashers import *


def loginview(request):
    return render(request, 'blog/IniciarSesion.html', {})
#@login_required
def administradores(request):
    return render(request, 'blog/administrador.html', {})
#@login_required
def administrador(request):
    return render(request, 'blog/administrador.html', {})


#@login_required
def blog(request):
    return render(request, 'blog/blog.html', {})

def ad(request):
    return render(request, 'blog/administrador.html', {})



def ListaVendedores(request):
    vendedores = Usuario.objects.all()
    return render(request, 'blog/listaVendedores.html', {'vendedores': vendedores})

def MantenedorOfertas(request):
    return render(request, 'blog/mantenedorOfertas.html', {})

def MantenedorTienda(request):
    return render(request, 'blog/mantenedorTienda.html', {})

def MantenedorVendedor(request):
    return render(request, 'blog/registroVendedor.html', {})

def Registrar_Vendedor(request):
    if request.method == 'POST':
        if request.POST.get('username') and request.POST.get('password'):
            post = Usuario()
            post.nombre = request.POST.get('nombre')
            post.apellido = request.POST.get('apellido')
            post.username = request.POST.get('username')
            encryptedpassword = make_password(request.POST.get('password'), hasher='default')
            post.password = encryptedpassword
            post.save()
            return render(request, 'blog/IniciarSesion.html')
        else:
            return render(request, 'blog/registroVendedor.html')

@csrf_protect
def login_user(request):
    logout(request)
    username = password = ''
    if request.POST:
        username = request.POST['username']
        password = request.POST['password']
        usuario = authenticate(username=username, password=password)
        if usuario is not None:
            if usuario.is_active:
                if usuario.is_superuser:
                    login(request, usuario)
                    return HttpResponseRedirect('/administrador')
                else:
                    return HttpResponseRedirect('/blog')
    return render(request, 'blog/IniciarSesion.html', {})

def registrarTienda(request):
    if request.method == 'POST':
        if request.POST.get('nombret'):
            post = Tienda()
            post.nombret = request.POST.get('nombret')
            post.direccion = request.POST.get('direccion')
            post.ciudad = request.POST.get('ciudad')
            post.comuna = request.POST.get('comuna')
            post.telefono = request.POST.get('telefono')
            post.encargado = request.POST.get('encargado')
            post.save()
            return render(request, 'blog/mantenedorTienda.html')
        else:
            return render(request, 'blog/mantenedorTienda.html')

def registrarOferta(request):
    if request.method == 'POST':
        if request.POST.get('valoroferta'):
            post = Oferta()
            post.Producto = request.POST.get('producto')
            post.valor_oferta = request.POST.get('valoroferta')
            post.save()
            return render(request, 'blog/mantenedorOfertas.html')
        else:
            return render(request, 'blog/mantenedorOfertas.html')

blog/templates/blog/IniciarSesion.html
{% load staticfiles %}
{% load static %}
{% load socialaccount %}

<!doctype html>
<html lang="en">
  <head>
    <title>Iniciar Sesion</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,700" rel="stylesheet"> 

    <link rel="stylesheet" href="css/bootstrap.css">
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">
    <link rel="stylesheet" href="css/owl.carousel.min.css">
    <link rel="stylesheet" href="css/magnific-popup.css">
    <script src="js/jquery.min.js"></script>


    

    <!--static fonts-->
    <link rel="stylesheet" href="{% static 'fonts/ionicons/css/ionicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/fontawesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/flaticon/font/flaticon.css' %}">


    <!--Archivos estaticos-->
    <link rel='stylesheet' type='text/css' href="{% static 'estilos.css' %}" />
    <link rel='stylesheet' type='text/css' href="{% static 'bootstrap.css' %}" />
    <link rel='stylesheet' type='text/css' href="{% static 'bootstrap-grid.css' %}" />
    <link rel='stylesheet' type='text/css' href="{% static 'bootstrap-reboot.css' %}" />
    <link rel='stylesheet' type='text/css' href="{% static 'bootstrap-min.css' %}" />
    <link rel='stylesheet' type='text/css' href="{% static 'bootstrap-grid-min.css' %}" />
    <link rel='stylesheet' type='text/css' href="{% static 'bootstrap-reboot.css' %}" />
    <link rel='stylesheet' type='text/css' href="{% static 'bootstrap-datepicker.min.css' %}" />
    <link rel='stylesheet' type='text/css' href="{% static 'bootstrap-datepicker.js' %}" />


    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'images' %}">
   
    
    <!-- Theme Style -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    
  </head>
  <body>
    
    <header role="banner">
     
      <nav class="navbar navbar-expand-md navbar-dark bg-light">
        <div class="container">
          <a class="navbar-brand" href="">PC Digital Factory Store</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample05" aria-controls="navbarsExample05" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

            
          </div>
        </div>
      </nav>
    </header>
    <!-- END header -->

    <section class="site-hero overlay" data-stellar-background-ratio="0.5" style="background-image: url(static/images/store.jpg);">
      <div class="container">
        <div class="row align-items-center site-hero-inner justify-content-center">
          <div class="col-md-8 text-center">

            <div class="mb-5 element-animate">
              <form name="iniciosesion" action="{% url 'login' %}" method="POST">
              {% csrf_token %}
                <label for="username">Nombre Usuario</label> <input id="fname" name="username" type="text" placeholder="Nombre de Usuario" maxlength="20" class="form-control"  required>
                <br>
                <label for="password">Contraseña</label> <input id="fname" name="password" type="password" placeholder="Contraseña" maxlength="16" class="form-control"  required>
                <br>
                <div class="form-group">
                  <div class="col-md-12 text-center">
                    <button type="submit" class="btn btn-primary btn-lg">Iniciar Sesion</button>
                  <hr>
                  



                  <button class="btn btn-secondary btn-block mt-5" type="submit">Sign in!</button>
<a class="btn btn-primary btn-block" href="{% provider_login_url "facebook" method="oauth2" %}">
   <span class="fab fa-facebook"></span>
      Login with facebook
 </a>

                  </div>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </section>

    
    <!-- END section -->

    
    <!-- END section -->


    
    <!-- END section -->



    <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'js/jquery-migrate-3.0.0.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
    <script src="{% static 'js/jquery.stellar.min.js' %}"></script>
    

    <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'js/magnific-popup-options.js' %}"></script>

    <script src="{% static 'js/main.js' %}"></script>
  </body>
</html>

blog/templates/blog/administrador.html
{% load staticfiles %}
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <title>Pc Digital </title>
    <!--VIENDO SI SE SUBE-->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Playfair+Display:400,700,900|Raleway" rel="stylesheet">
   <!--static fonts-->
   <link rel="stylesheet" href="{% static 'fonts/ionicons/css/ionicons.min.css' %}">
   <link rel="stylesheet" href="{% static 'fonts/fontawesome/css/font-awesome.min.css' %}">
   <link rel="stylesheet" href="{% static 'fonts/flaticon/font/flaticon.css' %}">


   <!--Archivos estaticos-->
   <link rel='stylesheet' type='text/css' href="{% static 'estilos.css' %}" />
   <link rel='stylesheet' type='text/css' href="{% static 'bootstrap.css' %}" />
   <link rel='stylesheet' type='text/css' href="{% static 'bootstrap-grid.css' %}" />
   <link rel='stylesheet' type='text/css' href="{% static 'bootstrap-reboot.css' %}" />
   <link rel='stylesheet' type='text/css' href="{% static 'bootstrap-min.css' %}" />
   <link rel='stylesheet' type='text/css' href="{% static 'bootstrap-grid-min.css' %}" />
   <link rel='stylesheet' type='text/css' href="{% static 'bootstrap-reboot.css' %}" />
   <link rel='stylesheet' type='text/css' href="{% static 'bootstrap-datepicker.min.css' %}" />
   <link rel='stylesheet' type='text/css' href="{% static 'bootstrap-datepicker.js' %}" />

   <!---->
   <link rel='stylesheet' type='text/css' href="{% static 'css/animate.css' %}" />
   <link rel='stylesheet' type='text/css' href="{% static 'css/owl.carousel.mun.css' %}" />

   <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
   <link rel="stylesheet" href="{% static 'images' %}">
  
   
   <!-- Theme Style -->
   <link rel="stylesheet" href="{% static 'css/style.css' %}">
  </head>
  <body>
    
    <header role="banner">
     
      <nav class="navbar navbar-expand-md navbar-dark bg-light">
        <div class="container">
          <a class="navbar-brand" href="{% url 'administrador' %}">PC Digital Factory Store</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample05" aria-controls="navbarsExample05" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse navbar-light" id="navbarsExample05">
            <ul class="navbar-nav ml-auto pl-lg-5 pl-0">
              <li class="nav-item">
                <a class="nav-link active" href="{% url 'ListaVendedores' %}">Lista de Vendedores</a>
              </li>
              <!--<li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="hairstyle.html" id="dropdown04" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Productos</a>
                <div class="dropdown-menu" aria-labelledby="dropdown04">
                  <a class="dropdown-item" href="hairstyle.html">Computación</a>
                  <a class="dropdown-item" href="hairstyle.html">Periféricos</a>
                  <a class="dropdown-item" href="hairstyle.html">Smartphones</a>
                  <a class="dropdown-item" href="hairstyle.html">Linea Blanca</a>
                  <a class="dropdown-item" href="hairstyle.html">Tarjetas Graficas</a>
                </div>
 
              </li>-->
              <li class="nav-item">
                <a class="nav-link active" href="{% url 'LoginUsuario' %}">Cerrar Sesion</a>
              </li>
            </ul>
            
          </div>
        </div>
      </nav>
      
    </header>
    <!-- END header -->

    
    <section class="site-hero site-hero-innerpage overlay" data-stellar-background-ratio="0.5" style="background-image: url('static/images/store.jpg');">
      <div class="container">
        <div class="row align-items-center site-hero-inner justify-content-center">
          <div class="col-md-8 text-center">

            <div class="mb-5 element-animate">
              <h1>Admin</h1>
            </div>

            
          </div>
        </div>
      </div>
    </section>
    <!-- END section -->

   

   
    <footer class="site-footer">
      <div>
          <!--INICIO FORMULARIO EN BOOTSTRAP-->

          <form name="form1" onchange="javascript:return Rut(document.form1.rut.value)">
              <div class="modal fade" id="modalContactForm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                   <div class="modal-dialog" role="document">
                       <div class="modal-content">
                           <div class="modal-header text-center">
                               <h4 class="modal-title w-100 font-weight-bold">Ingresa tu Venta</h4>
                               <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                   <span aria-hidden="true">&times;</span>
                               </button>
                           </div>
                           <div class="modal-body mx-3">
                              <form id="formularios" name="formularioUsuario" action="#">
                                  <label>Codigo Producto</label> 
                                  <input id="fname" name="sku" type="text" placeholder="Codigo" class="form-control" min="2" maxlength="6" required>
                                  <br>

                                  <label>Cantidad</label> 
                                  <input id="fname" name="cant" type="number"  placeholder="Ingrese la cantidad" class="form-control"  min="1" max="100" required>
                                  <br>

                                  <label>Total</label> 
                                  <input id="fname" name="total" type="text"  placeholder="Total de la venta" class="form-control" required>
                                  <br>

                                  <label>Comentario</label> 
                                  <input id="fname" name="coment" type="text"  placeholder="...." class="form-control"  maxlength="100">

                                  <br>
                                  <div class="form-group">
                                      <div class="col-md-12 text-center">
                                              <input type="submit"  value="Registrar"/>
                                      </div>
                                  </div>
                           </div>
                           
                       </div>
                   </div>
               </div>
  
               <div class="form-group">
                <div class="col-md-12 text-center">
                    <!--<button type="submit" class="btn btn-primary btn-lg">Iniciar Sesion</button>-->
                    <a href="{% url 'MantenedorOfertas' %}" class="btn btn-primary btn-lg">Ingresar Oferta</a>
               </div>
            </div>
            <div class="form-group">
              <div class="col-md-12 text-center">
                  <!--<button type="submit" class="btn btn-primary btn-lg">Iniciar Sesion</button>-->
                  <a href="{% url 'MantenedorVendedor' %}" class="btn btn-primary btn-lg">Ingresar Vendedor</a>
             </div>
          </div>
          <div class="form-group">
            <div class="col-md-12 text-center">
                <!--<button type="submit" class="btn btn-primary btn-lg">Iniciar Sesion</button>-->
                <a href="{% url 'MantenedorTienda' %}" class="btn btn-primary btn-lg">Ingresar Tienda</a>
           </div>
        </div>
           </form>
   </div>
   <!--FIN FORMULARIO-->
  
       
      </div>
    </footer>
    

    <!-- END footer -->
    
    <!-- loader -->
    <div id="loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#f4b214"/></svg></div>

    <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'js/jquery-migrate-3.0.0.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
    <script src="{% static 'js/jquery.stellar.min.js' %}"></script>
    

    <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'js/magnific-popup-options.js' %}"></script>

    <script src="{% static 'js/main.js' %}"></script>
  </body>
</html>

blog/templates/blog/mantenedorTienda.html
{% load staticfiles %}
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <title>Mantenedor Tienda</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,700" rel="stylesheet"> 

      <!--static fonts-->
      <link rel="stylesheet" href="{% static 'fonts/ionicons/css/ionicons.min.css' %}">
      <link rel="stylesheet" href="{% static 'fonts/fontawesome/css/font-awesome.min.css' %}">
      <link rel="stylesheet" href="{% static 'fonts/flaticon/font/flaticon.css' %}">
  
  
      <!--Archivos estaticos-->
      <link rel='stylesheet' type='text/css' href="{% static 'estilos.css' %}" />
      <link rel='stylesheet' type='text/css' href="{% static 'bootstrap.css' %}" />
      <link rel='stylesheet' type='text/css' href="{% static 'bootstrap-grid.css' %}" />
      <link rel='stylesheet' type='text/css' href="{% static 'bootstrap-reboot.css' %}" />
      <link rel='stylesheet' type='text/css' href="{% static 'bootstrap-min.css' %}" />
      <link rel='stylesheet' type='text/css' href="{% static 'bootstrap-grid-min.css' %}" />
      <link rel='stylesheet' type='text/css' href="{% static 'bootstrap-reboot.css' %}" />
      <link rel='stylesheet' type='text/css' href="{% static 'bootstrap-datepicker.min.css' %}" />
      <link rel='stylesheet' type='text/css' href="{% static 'bootstrap-datepicker.js' %}" />
  
      <!---->
      <link rel='stylesheet' type='text/css' href="{% static 'css/animate.css' %}" />
      <link rel='stylesheet' type='text/css' href="{% static 'css/owl.carousel.mun.css' %}" />
  
      <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
      <link rel="stylesheet" href="{% static 'images' %}">
      <link rel="stylesheet" href="{% static 'valida.js'%}">
     
      
      <!-- Theme Style -->
      <link rel="stylesheet" href="{% static 'css/style.css' %}">
  </head>
  <body>
    
    <header role="banner">
     
      <nav class="navbar navbar-expand-md navbar-dark bg-light">
        <div class="container">
          <a class="navbar-brand" href="{% url 'administrador' %}">PC Digital Factory Store</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample05" aria-controls="navbarsExample05" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse navbar-light" id="navbarsExample05">
              <ul class="navbar-nav ml-auto pl-lg-5 pl-0">
                <li class="nav-item">
                  <a class="nav-link active" href="{% url 'administrador' %}">Inicio</a>
                </li>
                
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'login' %}">Cerrar Sesion</a>
                </li>
              </ul>
            
          </div>
        </div>
      </nav>
    </header>
    <!-- END header -->
    <section class="site-hero overlay" data-stellar-background-ratio="0.5" style="background-image: url('static/images/store.jpg');">
      <div class="container">
        <div class="row align-items-center site-hero-inner justify-content-center">
          <div class="col-md-8 text-center">

            <div class="mb-5 element-animate">
              <h1 class="mb-4">Modulo de Tiendas</h1>
              
            </div>

          </div>
        </div>
      </div>
    </section>
    <!-- END section -->

    <section class="site-hero overlay" data-stellar-background-ratio="0.5" style="background-image: url(images/store.jpg);">
      <div class="container">
        <div class="row align-items-center site-hero-inner justify-content-center">
          <div class="col-md-8 text-center">

            <div class="mb-5 element-animate">
                <form name="formularioUsuario" id="tienda_form" action="{% url 'RegistrarTienda' %}" method="POST">
                    {% csrf_token %}
                    <label for="nombret">Nombre Tienda</label> 
                    <input id="fname" name="nombret" type="text" placeholder="Nombre Tienda" class="form-control" min="2" maxlength="15" required autofocus="Ingrese minimo 2 caracteres">
                    <br>
                    
                    <label for="direccion">Direccion</label> 
                    <input id="fname" name="direccion" type="text"  placeholder="Direccion" class="form-control"  maxlength="15" required autofocus="Ingrese minimo 2 caracteres">
                    
                    <label for="ciudad" data-error="wrong" data-success="right" for="form32">Seleccione Ciudad</label>
                                <select float="right" class="form-control validate" name="ciudad" id="regiones"></select>
                                
  
                                <label for="comuna" data-error="wrong" data-success="right" for="form32">Seleccione Comuna</label>
                                <select float="right" class="form-control validate" name="comuna" id="comunas" id="comunas"></select>
                    <br>
                    <label for="telefono">Telefono</label> 
                    <input id="fname" name="telefono" type="text" placeholder="+56999999999" class="form-control" minlength="4" maxlength="30" required autofocus="Ingrese minimo 4 caracteres">
                    
                  
                    <!--<label for="encargado">Encargado</label>                
                      <select id="vendedores" float="right" class="form-control validate">
                        {% for usuario in usuario %}
                        <option>{{usuario.nombre}}</option>
                        {% endfor %}
                      </select>-->
                      <br>
                    <label>Encargado</label> 
                    <input id="fname" name="encargado" type="text" placeholder="" class="form-control" minlength="4" maxlength="30" required autofocus="Ingrese minimo 4 caracteres" id="id_encargado">


                    <br>
                    <div class="form-group">
                        <div class="col-md-12 text-center">
                                <input type="submit"  value="Registrar"/>
                        </div>
                    </div>
            </div>

          </div>
        </div>
      </div>
    </section>
    <!-- END section -->

    


   
 
    
    <!-- loader -->
    <div id="loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#f4b214"/></svg></div>

    <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'js/jquery-migrate-3.0.0.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
    <script src="{% static 'js/jquery.stellar.min.js' %}"></script>
    

    <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'js/magnific-popup-options.js' %}"></script>

    <script src="{% static 'js/main.js' %}"></script>

    <script src="{% static 'js/valida.js' %}"></script>
    <script src="{% static 'js/valiar.js' %}"></script>

  </body>
</html>